[package]
name = "mtanzaku"
version = "0.1.1"
edition = "2021"
authors = ["mirko-san https://github.com/mirko-san"]
license = "MIT"
description = "tanzaku maker by mirko"
repository = "https://github.com/mirko-san/mtanzaku"

[dependencies]
